export { Refs };
const Refs = {
  userInput: document.querySelector('[name="searchQuery"]'),
  gallery: document.querySelector('.gallery'),
  submitButton: document.querySelector('[type="submit"]'),
  requestForm: document.querySelector('#search-form'),
  loadMoreButton: document.querySelector('.load-more'),
  favoritesBtn: document.querySelector('.lang-favorites'),
  homeBtn: document.querySelector('.lang-home'),
  goUpBtn: document.querySelector('.go-up-btn'),
  heder: document.querySelector('.heder'),
  body: document.querySelector('body'),
  checkbox: document.querySelector('#theme-switch-toggle'),
  footer: document.querySelector('.footer-container'),
  languageSwitch: document.querySelector('.language-switch__toggle'),
  languagesList: document.querySelector('.languages-list'),
  currentLanguage: document.querySelector('.language-switch__track'),
  picturesBtn: document.querySelector('.lang-picturesBtn'),
  videoBtn: document.querySelector('.lang-videoBtn'),
  imgListIcon: document.querySelector('.img-list-icon'),
  imgTypesList: document.querySelector('.img-types'),
};
